import React, { useState, useEffect } from "react";
import {
  View,
  Text,
  StyleSheet,
  Modal,
  TouchableOpacity,
  ScrollView,
  Alert,
  Dimensions,
  TextInput,
  Image,
  Share,
} from "react-native";
import { LinearGradient } from "expo-linear-gradient";
import { 
  X, 
  Sparkles, 
  Users, 
  Brain, 
  ChevronRight,
  ChevronLeft,
  BookOpen,
  Save,
  Share as ShareIcon,
} from "lucide-react-native";
import { useStories } from "@/contexts/StoriesContext";
import Colors from "@/constants/colors";

const { width: screenWidth, height: screenHeight } = Dimensions.get('window');

interface Chapter {
  title: string;
  text: string;
  image?: string;
}

interface StoryData {
  title: string;
  content: string;
  genre: string;
  readingTime: string;
  chapters: Chapter[];
}

// Mock story generator
const generateMockStory = (prompt: string, chapterCount: number): {title: string; chapters: Chapter[]} => {
  const titles = [
    "The Enchanted Forest Adventure",
    "Mystery of the Lost Kingdom", 
    "Journey Through Time",
    "The Dragon's Secret",
    "Quest for the Golden Crown"
  ];
  
  const title = titles[Math.floor(Math.random() * titles.length)];
  const chapters: Chapter[] = [];
  
  for (let i = 1; i <= chapterCount; i++) {
    chapters.push({
      title: `Chapter ${i}: The Adventure Continues`,
      text: `This is Chapter ${i} of your story "${title}". The story unfolds with exciting twists and turns, bringing our heroes closer to their ultimate goal. Based on your prompt: "${prompt}", this chapter explores themes of courage, friendship, and discovery.\n\nThe characters face new challenges and must work together to overcome obstacles. Each step brings them closer to understanding the true nature of their quest and the importance of their mission.\n\nAs the chapter concludes, readers are left eager to discover what happens next in this captivating tale.`
    });
  }
  
  return { title, chapters };
};

export const AIStoryGeneratorSimple: React.FC<{ visible: boolean; onClose: () => void; }> = ({ visible, onClose }) => {
  const { addStory } = useStories();
  const [prompt, setPrompt] = useState<string>("");
  const [selectedGenre, setSelectedGenre] = useState<string>("");
  const [selectedLength, setSelectedLength] = useState<string>("");
  const [isGenerating, setIsGenerating] = useState<boolean>(false);
  const [generatedStory, setGeneratedStory] = useState<StoryData | null>(null);
  const [showStory, setShowStory] = useState<boolean>(false);
  const [isSaved, setIsSaved] = useState<boolean>(false);
  const [showSummary, setShowSummary] = useState<boolean>(false);
  
  // Pagination states
  const [currentPage, setCurrentPage] = useState<number>(0);
  const [totalPages, setTotalPages] = useState<number>(1);
  const [storyPages, setStoryPages] = useState<Chapter[][]>([]);

  const genres = ["Adventure", "Mystery", "Sci-Fi", "Fantasy", "Romance", "Horror", "Comedy", "Drama"];
  const lengths = ["Short (5-10 min)", "Medium (10-15 min)", "Long (15-20 min)"];
  
  // Helper function to split story into pages
  const paginateStory = (chapters: Chapter[]): Chapter[][] => {
    const chaptersPerPage = 2;
    const pages: Chapter[][] = [];
    for (let i = 0; i < chapters.length; i += chaptersPerPage) {
      pages.push(chapters.slice(i, i + chaptersPerPage));
    }
    return pages.length > 0 ? pages : [[]];
  };

  // Save story to home page
  const handleSaveStory = () => {
    if (!generatedStory) return;

    try {
      const storyToSave = {
        id: Date.now().toString(),
        title: generatedStory.title,
        duration: generatedStory.readingTime,
        author: "Echo AI",
        imageUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=500&h=300&fit=crop",
        category: generatedStory.genre,
        content: generatedStory.content,
        images: [],
      };

      addStory(storyToSave);
      setIsSaved(true);
      Alert.alert(
        "Story Saved!",
        "Your story has been saved to your library and will appear on the home page.",
        [{ text: "OK", style: "default" }]
      );
    } catch (error) {
      console.error('Error saving story:', error);
      Alert.alert("Save Failed", "Unable to save story. Please try again.");
    }
  };

  // Share story functionality
  const handleShareStory = async () => {
    if (!generatedStory) return;

    try {
      const shareContent = `📚 ${generatedStory.title}

${generatedStory.chapters[0]?.text.substring(0, 200)}...

Generated by Echo AI Story Generator`;
      
      await Share.share({
        message: shareContent,
        title: generatedStory.title,
      });
    } catch (error) {
      console.error('Error sharing story:', error);
      Alert.alert("Share Failed", "Unable to share story. Please try again.");
    }
  };

  // Generate story
  const generateStory = async () => {
    const finalGenre = selectedGenre || "Adventure";
    const finalLength = selectedLength || "Short (5-10 min)";
    const finalPrompt = prompt?.trim() || `A ${finalGenre.toLowerCase()} story`;

    setIsGenerating(true);

    try {
      // Simulate AI generation delay
      await new Promise(resolve => setTimeout(resolve, 2000));
      
      const chapterCount = finalLength === "Short (5-10 min)" ? 3 : finalLength === "Medium (10-15 min)" ? 5 : 7;
      const { title, chapters } = generateMockStory(finalPrompt, chapterCount);
      
      const storyData: StoryData = {
        title,
        content: chapters.map(ch => ch.text).join('\n\n'),
        genre: finalGenre,
        readingTime: finalLength,
        chapters,
      };

      // Setup pagination
      const pages = paginateStory(chapters);
      setStoryPages(pages);
      setTotalPages(pages.length);
      setCurrentPage(0);

      setGeneratedStory(storyData);
      setIsGenerating(false);
      setShowStory(true);
      setIsSaved(false);
      
    } catch (error) {
      console.error('Story generation failed:', error);
      setIsGenerating(false);
      Alert.alert("Generation Failed", "Unable to generate story. Please try again.");
    }
  };

  const nextPage = () => {
    if (currentPage < totalPages - 1) {
      setCurrentPage(currentPage + 1);
    }
  };

  const prevPage = () => {
    if (currentPage > 0) {
      setCurrentPage(currentPage - 1);
    }
  };

  const resetGenerator = () => {
    setGeneratedStory(null);
    setShowStory(false);
    setCurrentPage(0);
    setShowSummary(false);
  };

  if (!visible) return null;

  return (
    <Modal
      visible={visible}
      animationType="slide"
      presentationStyle="pageSheet"
      onRequestClose={onClose}
    >
      <View style={styles.container}>
        <LinearGradient
          colors={['#667eea', '#764ba2']}
          start={{ x: 0, y: 0 }}
          end={{ x: 1, y: 1 }}
          style={styles.header}
        >
          <View style={styles.headerContent}>
            <TouchableOpacity
              style={styles.closeButton}
              onPress={showStory ? resetGenerator : onClose}
            >
              {showStory ? <ChevronLeft size={24} color="white" /> : <X size={24} color="white" />}
            </TouchableOpacity>
            <Text style={styles.headerTitle}>
              {showStory ? "Story Reader" : "AI Story Generator"}
            </Text>
            {showStory && (
              <TouchableOpacity
                style={styles.headerButton}
                onPress={() => setShowSummary(true)}
              >
                <Image
                  source={require('../assets/images/writing.png')}
                  style={styles.headerIcon}
                  resizeMode="contain"
                />
              </TouchableOpacity>
            )}
          </View>
        </LinearGradient>

        <ScrollView style={styles.content} showsVerticalScrollIndicator={false}>
          {!showStory ? (
            // Generator Interface
            <View style={styles.generatorContainer}>
              {!isGenerating ? (
                <View>
                  <View style={styles.inputSection}>
                    <Text style={styles.sectionTitle}>
                      <Sparkles size={16} color={Colors.primary} /> Your Story Idea
                    </Text>
                    <View style={styles.inputWrapper}>
                      <TextInput
                        style={styles.textInput}
                        placeholder="Enter your story idea (optional)"
                        placeholderTextColor="#9CA3AF"
                        value={prompt}
                        onChangeText={setPrompt}
                        multiline
                        maxLength={500}
                      />
                      <View style={styles.inputFooter}>
                        <Text style={styles.characterCount}>{prompt.length}/500</Text>
                      </View>
                    </View>
                  </View>

                  <View style={styles.selectionContainer}>
                    <Text style={styles.label}>Genre</Text>
                    <ScrollView horizontal showsHorizontalScrollIndicator={false}>
                      <View style={styles.optionsRow}>
                        {genres.map((genre) => (
                          <TouchableOpacity
                            key={genre}
                            style={[styles.optionButton, selectedGenre === genre && styles.selectedOption]}
                            onPress={() => setSelectedGenre(genre)}
                          >
                            <Text style={[styles.optionText, selectedGenre === genre && styles.selectedText]}>
                              {genre}
                            </Text>
                          </TouchableOpacity>
                        ))}
                      </View>
                    </ScrollView>
                  </View>

                  <View style={styles.selectionContainer}>
                    <Text style={styles.label}>Length</Text>
                    <ScrollView horizontal showsHorizontalScrollIndicator={false}>
                      <View style={styles.optionsRow}>
                        {lengths.map((length) => (
                          <TouchableOpacity
                            key={length}
                            style={[styles.optionButton, selectedLength === length && styles.selectedOption]}
                            onPress={() => setSelectedLength(length)}
                          >
                            <Text style={[styles.optionText, selectedLength === length && styles.selectedText]}>
                              {length}
                            </Text>
                          </TouchableOpacity>
                        ))}
                      </View>
                    </ScrollView>
                  </View>

                  <View style={styles.generateSection}>
                    <TouchableOpacity
                      style={styles.generateButton}
                      onPress={generateStory}
                    >
                      <LinearGradient
                        colors={[Colors.primary, '#8B5CF6', '#06B6D4']}
                        start={{ x: 0, y: 0 }}
                        end={{ x: 1, y: 0 }}
                        style={styles.buttonGradient}
                      >
                        <Sparkles size={20} color="white" />
                        <Text style={styles.generateButtonText}>Generate Story</Text>
                      </LinearGradient>
                    </TouchableOpacity>
                  </View>
                </View>
              ) : (
                <View style={styles.generationContainer}>
                  <View style={styles.aiAnimationContainer}>
                    <Brain size={48} color={Colors.primary} />
                    <Text style={styles.aiText}>AI is creating your story...</Text>
                  </View>
                </View>
              )}
            </View>
          ) : (
            // Story Reader
            <View style={styles.readerContainer}>
              <ScrollView contentContainerStyle={styles.readerScrollContent}>
                <Text style={styles.readerMainTitle}>{generatedStory?.title}</Text>
                
                {storyPages[currentPage]?.map((chapter, index) => (
                  <View key={`${currentPage}-${index}`} style={styles.readerChapterContainer}>
                    <Text style={styles.readerChapterTitle}>{chapter.title}</Text>
                    <Text style={styles.readerBody}>{chapter.text}</Text>
                  </View>
                ))}
              </ScrollView>

              {/* Navigation */}
              <View style={styles.readerNavigation}>
                <TouchableOpacity
                  style={[styles.navButton, currentPage === 0 && styles.navButtonDisabled]}
                  onPress={prevPage}
                  disabled={currentPage === 0}
                >
                  <ChevronLeft size={24} color={currentPage === 0 ? "#9CA3AF" : "white"} />
                </TouchableOpacity>

                <View style={styles.pageIndicator}>
                  <Text style={styles.pageText}>
                    {currentPage + 1} of {totalPages}
                  </Text>
                </View>

                <TouchableOpacity
                  style={[styles.navButton, currentPage === totalPages - 1 && styles.navButtonDisabled]}
                  onPress={nextPage}
                  disabled={currentPage === totalPages - 1}
                >
                  <Image
                    source={require('../assets/images/next.png')}
                    style={styles.nextIcon}
                    resizeMode="contain"
                  />
                </TouchableOpacity>
              </View>

              {/* Save and Share buttons */}
              <View style={styles.actionButtons}>
                <TouchableOpacity
                  style={[styles.actionButton, isSaved && styles.savedButton]}
                  onPress={handleSaveStory}
                  disabled={isSaved}
                >
                  <LinearGradient
                    colors={isSaved ? ['#10B981', '#10B981'] : [Colors.primary, '#8B5CF6']}
                    style={styles.actionButtonGradient}
                  >
                    <Save size={20} color="white" />
                    <Text style={styles.actionButtonText}>
                      {isSaved ? "Saved!" : "Save Story"}
                    </Text>
                  </LinearGradient>
                </TouchableOpacity>

                <TouchableOpacity
                  style={styles.actionButton}
                  onPress={handleShareStory}
                >
                  <LinearGradient
                    colors={['#EC4899', '#F97316']}
                    style={styles.actionButtonGradient}
                  >
                    <ShareIcon size={20} color="white" />
                    <Text style={styles.actionButtonText}>Share Story</Text>
                  </LinearGradient>
                </TouchableOpacity>
              </View>
            </View>
          )}
        </ScrollView>

        {/* Summary Modal */}
        <Modal
          visible={showSummary}
          animationType="slide"
          presentationStyle="pageSheet"
          onRequestClose={() => setShowSummary(false)}
        >
          <View style={styles.summaryContainer}>
            <LinearGradient
              colors={['#667eea', '#764ba2']}
              style={styles.summaryHeader}
            >
              <View style={styles.summaryHeaderContent}>
                <TouchableOpacity
                  style={styles.closeButton}
                  onPress={() => setShowSummary(false)}
                >
                  <X size={24} color="white" />
                </TouchableOpacity>
                <Text style={styles.summaryTitle}>Story Summary</Text>
                <View style={styles.closeButton} />
              </View>
            </LinearGradient>
            
            <ScrollView style={styles.summaryContent}>
              {generatedStory && (
                <View style={styles.summaryDetails}>
                  <Text style={styles.summaryStoryTitle}>{generatedStory.title}</Text>
                  
                  <View style={styles.summaryMeta}>
                    <Text style={styles.summaryMetaText}>Genre: {generatedStory.genre}</Text>
                    <Text style={styles.summaryMetaText}>Reading Time: {generatedStory.readingTime}</Text>
                    <Text style={styles.summaryMetaText}>Chapters: {generatedStory.chapters.length}</Text>
                  </View>

                  <View style={styles.summarySection}>
                    <Text style={styles.summarySectionTitle}>Complete Story</Text>
                    <Text style={styles.summaryText}>{generatedStory.content}</Text>
                  </View>

                  <View style={styles.summarySection}>
                    <Text style={styles.summarySectionTitle}>Chapter Breakdown</Text>
                    {generatedStory.chapters.map((chapter, index) => (
                      <View key={index} style={styles.summaryChapterItem}>
                        <Text style={styles.summaryChapterTitle}>{chapter.title}</Text>
                        <Text style={styles.summaryChapterPreview}>
                          {chapter.text.substring(0, 100)}...
                        </Text>
                      </View>
                    ))}
                  </View>
                </View>
              )}
            </ScrollView>
          </View>
        </Modal>
      </View>
    </Modal>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  header: {
    paddingTop: 50,
    paddingBottom: 20,
    paddingHorizontal: 20,
  },
  headerContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  closeButton: {
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: 'white',
  },
  headerButton: {
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerIcon: {
    width: 24,
    height: 24,
    tintColor: 'white',
  },
  content: {
    flex: 1,
  },
  generatorContainer: {
    padding: 20,
  },
  inputSection: {
    marginBottom: 30,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: Colors.text,
    marginBottom: 15,
    flexDirection: 'row',
    alignItems: 'center',
  },
  inputWrapper: {
    backgroundColor: '#F8FAFC',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  textInput: {
    padding: 16,
    fontSize: 16,
    color: Colors.text,
    minHeight: 100,
    textAlignVertical: 'top',
  },
  inputFooter: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    padding: 8,
    borderTopWidth: 1,
    borderTopColor: '#E2E8F0',
  },
  characterCount: {
    fontSize: 12,
    color: Colors.mutedText,
  },
  selectionContainer: {
    marginBottom: 25,
  },
  label: {
    fontSize: 16,
    fontWeight: '600',
    color: Colors.text,
    marginBottom: 12,
  },
  optionsRow: {
    flexDirection: 'row',
    paddingHorizontal: 4,
  },
  optionButton: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    backgroundColor: '#F1F5F9',
    borderRadius: 20,
    marginRight: 10,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  selectedOption: {
    backgroundColor: Colors.primary,
    borderColor: Colors.primary,
  },
  optionText: {
    fontSize: 14,
    fontWeight: '500',
    color: Colors.text,
  },
  selectedText: {
    color: 'white',
  },
  generateSection: {
    marginTop: 20,
  },
  generateButton: {
    borderRadius: 25,
    overflow: 'hidden',
  },
  buttonGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 16,
    paddingHorizontal: 32,
  },
  generateButtonText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: 'white',
    marginLeft: 8,
  },
  generationContainer: {
    alignItems: 'center',
    paddingVertical: 50,
  },
  aiAnimationContainer: {
    alignItems: 'center',
    marginBottom: 20,
  },
  aiText: {
    fontSize: 16,
    fontWeight: '500',
    color: Colors.text,
    marginTop: 16,
  },
  readerContainer: {
    flex: 1,
  },
  readerScrollContent: {
    padding: 20,
    paddingBottom: 100,
  },
  readerMainTitle: {
    fontSize: 28,
    fontWeight: 'bold',
    color: Colors.text,
    textAlign: 'center',
    marginBottom: 30,
  },
  readerChapterContainer: {
    marginBottom: 30,
  },
  readerChapterTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: Colors.primary,
    marginBottom: 15,
  },
  readerBody: {
    fontSize: 16,
    lineHeight: 24,
    color: Colors.text,
  },
  readerNavigation: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 15,
    backgroundColor: 'white',
    borderTopWidth: 1,
    borderTopColor: '#E2E8F0',
  },
  navButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: Colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  navButtonDisabled: {
    backgroundColor: '#E2E8F0',
  },
  nextIcon: {
    width: 24,
    height: 24,
    tintColor: 'white',
  },
  pageIndicator: {
    backgroundColor: '#F1F5F9',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 16,
  },
  pageText: {
    fontSize: 14,
    fontWeight: '500',
    color: Colors.text,
  },
  actionButtons: {
    flexDirection: 'row',
    paddingHorizontal: 20,
    paddingVertical: 15,
    gap: 10,
  },
  actionButton: {
    flex: 1,
    borderRadius: 20,
    overflow: 'hidden',
  },
  savedButton: {
    opacity: 0.8,
  },
  actionButtonGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
  },
  actionButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: 'white',
    marginLeft: 6,
  },
  summaryContainer: {
    flex: 1,
    backgroundColor: 'white',
  },
  summaryHeader: {
    paddingTop: 50,
    paddingBottom: 20,
    paddingHorizontal: 20,
  },
  summaryHeaderContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  summaryTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: 'white',
  },
  summaryContent: {
    flex: 1,
    padding: 20,
  },
  summaryDetails: {
    flex: 1,
  },
  summaryStoryTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: Colors.primary,
    textAlign: 'center',
    marginBottom: 20,
  },
  summaryMeta: {
    backgroundColor: '#F8FAFC',
    padding: 16,
    borderRadius: 12,
    marginBottom: 20,
  },
  summaryMetaText: {
    fontSize: 14,
    color: Colors.text,
    marginBottom: 4,
  },
  summarySection: {
    marginBottom: 25,
  },
  summarySectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: Colors.text,
    marginBottom: 12,
  },
  summaryText: {
    fontSize: 16,
    lineHeight: 24,
    color: Colors.text,
  },
  summaryChapterItem: {
    backgroundColor: '#F8FAFC',
    borderRadius: 8,
    padding: 12,
    marginBottom: 8,
  },
  summaryChapterTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: Colors.primary,
    marginBottom: 4,
  },
  summaryChapterPreview: {
    fontSize: 14,
    color: Colors.mutedText,
  },
});

export default AIStoryGeneratorSimple;